### ISSUE TITLE
Typed Signatures Unicode Problem with Greek Characters

### ISSUE THREAD

**Issue by ArbiterGR** [documenso/documenso#1646]
### Issue Description

Since 1.8.0, if we use Greek text for typing a signature, the result pdf has weird boxes like this instead of the signature text: 

![Image](https://github.com/user-attachments/assets/60c1ae79-5df3-433a-8f02-10193ab5726b)

### Steps to Reproduce

Enable typed signatures and use Greek characters in a typed signature field.

### Expected Behavior

It should render unicode characters as expected.

### Current Behavior

It does not render unicode characters as expected.

### Screenshots (optional)

![Image](https://github.com/user-attachments/assets/27815c37-c3b5-443c-8564-ba6c50b8e8e8)

### Please check the boxes that apply to this issue report.

- [x] I have searched the existing issues to make sure this is not a duplicate.
- [x] I have provided steps to reproduce the issue.
- [x] I have included relevant environment information.
- [x] I have included any relevant screenshots.
- [x] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by aminsharifi** [comment]
I have the same problem with non English characters, please support UTF-8 in signature name

**Comment by ephraimduncan** [comment]
Fixed. PDF rendering now uses `@cantoo/pdf-lib` with `fontkit` and embeds Noto Sans, which includes Greek script support (confirmed via binary analysis of the `grek` script tag in the font file). The old `StandardFontEmbedder` / WinAnsi path that caused this is no longer used.

**Comment by dima19972525** [comment]
@ephraimduncan hi, do we know if this fix will be included in 2.8.2 version?
++ Do we know when will be the new release?

**Comment by AbdelrhmanAbdelhamed** [comment]
Hello @ephraimduncan @Mythie 
This is still an issue, we're having the same problem with non English / Greek / Chinese characters

**Comment by dima19972525** [comment]
Hi @ephraimduncan , It seems like the issue still exists in 2.9.1 version

<img width="1116" height="430" alt="Image" src="https://github.com/user-attachments/assets/80eae1ca-16ed-43ea-af39-10449961637d" />

**Comment by AbdelrhmanAbdelhamed** [comment]
Opened #2728 with a fix.

**Root cause:** typed signatures always render with the Caveat handwriting font, which only covers ASCII. Every other script — Greek (this issue), Hebrew, Arabic, Indic, Thai, CJK, Japanese kana, Korean Hangul, etc. — produces no glyph and renders as `□□□` in the sealed PDF.

The bug is in the **default V2** envelope pipeline (Konva / skia-canvas) and in the **signing certificate** that's attached to every sealed PDF (V1 and V2).

**Fix:** extend the typed-signature `fontFamily` from `'Caveat, sans-serif'` to a chain that includes the four Noto Sans variants already shipped in `apps/remix/public/fonts/` and already registered with skia-canvas. A tiny helper picks **one** font for the whole signature: Caveat if the text is pure ASCII, otherwise the Noto chain. All-or-nothing on purpose — a signature is never half-handwriting / half-sans-serif.

The Noto chain orders Chinese before Japanese so pure-Chinese text gets CN glyph shapes (the Japanese font also contains Han ideographs for kanji with JP-specific shapes). Scripts where no dedicated Noto file is shipped (Ethiopic, Khmer, Mongolian, …) render via the chain's trailing `sans-serif`.

No new font assets. Applied to V2 field rendering and `render-certificate.ts`. The V1 pdf-lib path and the deprecated `legacy_insertFieldInPDF` are intentionally out of scope (pdf-lib doesn't walk a font fallback chain, so a proper V1 fix is a separate, more invasive change; the certificate page still renders correctly for V1 envelopes because the certificate goes through V2/skia-canvas).

Sealed PDF with all six scripts (`Ελληνικά / 도큐멘소 / 中文签名 / こんにちは / Иванов / John Doe`) on one page verified locally — all glyphs render correctly, no tofu.

Could this be reopened until the PR lands?
