### ISSUE TITLE
No Document found when trying to send a mail

### ISSUE THREAD

**Issue by UncleJ4ck** [documenso/documenso#1732]
### Issue Description

Im having issues when i upload a document and try to send it the documenso container shows these errors in the logs

`
documenso  | [JOBS]: Job send.signing.requested.email failed NotFoundError [PrismaClientKnownRequestError]: No Document found
documenso  |     at /app/node_modules/@prisma/client/runtime/library.js:34:609
documenso  |     at async /app/node_modules/@prisma/client/runtime/library.js:34:549
documenso  |     at async Promise.all (index 1)
documenso  |     at async Object.handler (/app/apps/web/.next/server/chunks/9783.js:1:21730)
documenso  |     at async /app/apps/web/.next/server/chunks/9783.js:1:17053
documenso  |     at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)
documenso  |     at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)
documenso  |     at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:600:9)
documenso  |     at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:269:37)
documenso  |     at async NextNodeServer.handleRequestImpl (/app/node_modules/next/dist/server/base-server.js:816:17) {
documenso  |   code: 'P2025',
documenso  |   clientVersion: '5.4.2',
documenso  |   meta: undefined
documenso  | }
documenso  | Submitting job to endpoint: http://documenso:3000/api/jobs/send.signing.requested.email/cm8t5ywk3000spd20njxhwie7
documenso  | [JOBS]: Triggering job send.signing.requested.email with payload {
documenso  |   userId: 3,
documenso  |   documentId: 18,
documenso  |   recipientId: 21,
documenso  |   requestMetadata: {
documenso  |     ipAddress: 'REDACTED',
documenso  |     userAgent: 'Mozilla/5.0 (X11; Linux x86_64; rv:136.0) Gecko/20100101 Firefox/136.0'
documenso  |   }
documenso  | }
documenso  | [JOBS]: Job send.signing.requested.email failed NotFoundError [PrismaClientKnownRequestError]: No Document found
documenso  |     at /app/node_modules/@prisma/client/runtime/library.js:34:609
documenso  |     at async /app/node_modules/@prisma/client/runtime/library.js:34:549
documenso  |     at async Promise.all (index 1)
documenso  |     at async Object.handler (/app/apps/web/.next/server/chunks/9783.js:1:21730)
documenso  |     at async /app/apps/web/.next/server/chunks/9783.js:1:17053
documenso  |     at async K (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:16853)
documenso  |     at async U.render (/app/node_modules/next/dist/compiled/next-server/pages-api.runtime.prod.js:20:17492)
documenso  |     at async NextNodeServer.runApi (/app/node_modules/next/dist/server/next-server.js:600:9)
documenso  |     at async NextNodeServer.handleCatchallRenderRequest (/app/node_modules/next/dist/server/next-server.js:269:37)
documenso  |     at async NextNodeServer.handleRequestImpl (/app/node_modules/next/dist/server/base-server.js:816:17) {
documenso  |   code: 'P2025',
documenso  |   clientVersion: '5.4.2',
documenso  |   meta: undefined
documenso  | }
documenso  | Submitting job to endpoint: http://documenso:3000/api/jobs/send.signing.requested.email/cm8t5ywk3000spd20njxhwie7
documenso  | [JOBS]: Triggering job send.signing.requested.email with payload {
documenso  |   userId: 3,
documenso  |   documentId: 18,
documenso  |   recipientId: 21,
documenso  |   requestMetadata: {
documenso  |     ipAddress: 'REDACTED',
documenso  |     userAgent: 'Mozilla/5.0 (X11; Linux x86_64; rv:136.0) Gecko/20100101 Firefox/136.0'
documenso  |   }
documenso  | }
`

i had at first an issue that's labeled `Task failed` but then i fixed it by generating the certificate with the `-legacy` option and the `chown 1001` so i tried to fix it really and i even added `NEXT_PRIVATE_INTERNAL_WEBAPP_URL`   
here's my .env and my docker compose: 
`services:
  ################################################################
  # Documenso – Document Signing Service & its PostgreSQL Database
  ################################################################
  documenso:
    image: documenso/documenso:latest
    container_name: documenso
    depends_on:
      documenso-postgres:
        condition: service_healthy
    volumes:
      - ./documenso:/opt/documenso/data
      - ./certificate.p12:/opt/documenso/cert.p12
    environment:
      - NEXTAUTH_SECRET=${NEXTAUTH_SECRET}
      - NEXT_PRIVATE_ENCRYPTION_KEY=${NEXT_PRIVATE_ENCRYPTION_KEY}
      - NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY=${NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY}
      - NEXT_PUBLIC_WEBAPP_URL=${NEXT_PUBLIC_WEBAPP_URL}
      - NEXT_PRIVATE_JOBS_PROVIDER=local
      - NEXTAUTH_URL=${NEXTAUTH_URL}
      - NEXT_PRIVATE_SMTP_TRANSPORT="smtp-auth"
      - NEXT_PRIVATE_SMTP_HOST=${NEXT_PRIVATE_SMTP_HOST}      
      - NEXT_PRIVATE_SMTP_PORT=${NEXT_PRIVATE_SMTP_PORT}    
      - NEXT_PRIVATE_SMTP_USERNAME=${NEXT_PRIVATE_SMTP_USERNAME}
      - NEXT_PRIVATE_SMTP_PASSWORD=${NEXT_PRIVATE_SMTP_PASSWORD}
      - NEXT_PRIVATE_SMTP_SECURE=false
      - NEXT_PRIVATE_SMTP_UNSAFE_IGNORE_TLS=false
      - NEXT_PRIVATE_DATABASE_URL=postgresql://postgres:postgres@documenso-postgres:5432/documenso
      - NEXT_PRIVATE_DIRECT_DATABASE_URL=postgresql://postgres:postgres@documenso-postgres:5432/documenso
      - NEXT_PRIVATE_SMTP_FROM_ADDRESS=no-reply@redacted.com
      - NEXT_PRIVATE_SMTP_FROM_NAME=redacted
      - NEXT_PRIVATE_INTERNAL_WEBAPP_URL=${NEXT_PRIVATE_INTERNAL_WEBAPP_URL}
      - NEXT_PUBLIC_DISABLE_SIGNUP=true
      - NEXT_PRIVATE_SIGNING_PASSPHRASE=${NEXT_PRIVATE_SIGNING_PASSPHRASE}
      - NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH=${NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH}
    restart: unless-stopped
    networks:
      internal:
        ipv4_address: 10.8.1.12

  documenso-postgres:
    image: postgres:latest
    container_name: documenso-postgres
    volumes:
      - ./pg_documenso:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: documenso
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped
    networks:
      internal:
        ipv4_address: 10.8.1.13
` 

env:

`# Documenso
NEXTAUTH_SECRET=mGAGrtja/W7NLrs*************************
NEXT_PRIVATE_ENCRYPTION_KEY=i8ez7KVnxXsmAXLXz/iIcv5********************
NEXT_PRIVATE_ENCRYPTION_SECONDARY_KEY=XVn2yVh1YA6oK*********************
NEXT_PRIVATE_SMTP_TRANSPORT=smtp-auth
NEXT_PRIVATE_SMTP_HOST=smtp.office365.com
NEXT_PRIVATE_SMTP_PORT=587
NEXT_PRIVATE_SMTP_USERNAME=no-reply@redacted.com
NEXT_PRIVATE_SMTP_PASSWORD=tN********************
NEXT_PUBLIC_WEBAPP_URL=https://pdf-redacted.duckdns.org
NEXTAUTH_URL=https://pdf-redacted.duckdns.org
NEXT_PRIVATE_SIGNING_PASSPHRASE=*******************
NEXT_PRIVATE_SIGNING_LOCAL_FILE_PATH=/opt/documenso/cert.p12
NEXT_PRIVATE_INTERNAL_WEBAPP_URL=http://documenso:3000
`

### Please check the boxes that apply to this issue report.

- [ ] I have searched the existing issues to make sure this is not a duplicate.
- [ ] I have provided steps to reproduce the issue.
- [ ] I have included relevant environment information.
- [ ] I have included any relevant screenshots.
- [ ] I understand that this is a voluntary contribution and that there is no guarantee of resolution.
- [ ] I want to work on creating a PR for this issue if approved

**Comment by fredhii** [comment]
Bro did you manage to solve the error?
I have the same issue

**Comment by UncleJ4ck** [comment]
i fixed the issue by pulling the real docker image because the latest tag it's not the real final version

**Comment by Shkelly-dot** [comment]
I still have this issue, and trying other docker images didn't solve it.. has anyone any other idea? i am trying for days now..

**Comment by ElTimuro** [comment]
- closing as stale and this should fix fixed
- let us know if there are still issues
